### ISSUE TITLE
Re-write to TypeScript

### ISSUE THREAD

**Issue by tanettrimas** [Tripletex/YesCommons#18]
Some of these functions can be quite hard to maintain after some time, could be useful to rewrite in TS to get rid of some JSDocs and type safety

**Comment by torland-klev** [comment]
Assign me please! 😁

**Comment by tanettrimas** [comment]
@torland-klev kjørr!!!

**Comment by torland-klev** [comment]
[Connected pull request](https://github.com/Tripletex/YesCommons/pull/29)

**Comment by torland-klev** [comment]
Solved? 😎
