### ISSUE TITLE
Modulo 11 in its own file/module

### ISSUE THREAD

**Issue by lebchen** [Tripletex/YesCommons#3]
Could be nice to have no external deps, so don't use an existing mod11. But we now have mod11 in two files, extract it to one file would be nice.

**Comment by ergor** [comment]
#6 added this lib, but it is currently unused in the project. We need to use it, or modify it until we can use it.

**Comment by tanettrimas** [comment]
I think this can be fixed by this PR: https://github.com/Tripletex/YesCommons/pull/7
